version: "3"
services:
  postgres:
    restart: always
    image: postgres:latest
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5431:5431"

  checker:
    restart: always
    build:
      context: .
      dockerfile: ./checker/Dockerfile
    depends_on:
      - postgres
    entrypoint: "python status_checker.py"

  api:
    restart: always
    build:
      context: .
      dockerfile: ./api/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - checker
    entrypoint: "python3 server.py runserver"
